### ISSUE TITLE
passing a formula fails?

### ISSUE THREAD

**Issue by alicerobson** [caldwellst/augury#2]
Sorry if I am being dopey. In any case would be great to have an example of using a formula in your lovely vignette.

#this works (use df_test from previous example)
 form<-value~year_n
   lm(form,df_test)

This does not
        tmp<-predict_lm(df_test,
                              formula = form,
					pred_col="pred",
					test_col="test_col",
							type_col = "type",
                          source_col = "source",
                          source = "augury modeling", 
						  ret="all") 

Error in parse_formula(formula) : 
  argument "formula" is missing, with no default

**Comment by caldwellst** [comment]
So this was a bug in not passing the formula object on to the general models, should work now.

```
library(augury)

df <- ghost::gho_data("SDGIHR2018") %>%
    billionaiRe::wrangle_gho_data() %>%
    dplyr::right_join(covariates_df) %>%
    arrange(iso3, year)

form <- value ~ year_n

predict_lm(df,
                   formula = form,
                   pred_col="pred",
                   test_col="test_col",
                   type_col = "type",
                   source_col = "source",
                   source = "augury modeling",
                   ret="all")
```

I've fixed a few other small issues I've noticed and this should now run, along with other general models. Ignore the fact I just chose the first GHO indicator that came to mind and the model and testing makes no sense ha.
